### ISSUE TITLE
Error when running the node

### ISSUE THREAD

**Issue by seboz123** [fabvio/ld-lsi#4]
Hi,
I am getting an error running the code. The Error appears in cnn_node.py in line 57:
` output = self.cnn(input_tensor)`
The exception thrown is as follows:
`Cannot obtain output. Exception: size mismatch, m1: [1 x 30720], m2: [7680 x 1024] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249`
Any ideas would be appreciated!

**Comment by fabvio** [comment]
Hi, what is the input size of your images?

**Comment by seboz123** [comment]
The input size is 1280x720

**Comment by fabvio** [comment]
Try to resize them to 640x360 ;)
