### ISSUE TITLE
request for training code

### ISSUE THREAD

**Issue by ma-siddiqui** [fabvio/ld-lsi#5]
Hi,

Its really awesome work. I need training script and code. May request for it. I am running the code without catkin, geometry_msgs and  rospy. Currently running your inference code using CUDA 10.1 Pytorch 1.3.0. Soon I will contribute all my new changes. Meanwhile, it would be great if you can share training code.

Thanks,
Muhammad Ajmal Siddiqui

**Comment by ma-siddiqui** [comment]
Hi,

Any update?

Thanks,
Ajmal Siddqui

**Comment by fabvio** [comment]
Hi. Code for training is now public, it has been coded by @khizar-anjum.
Right now it's not documented nor extensively tested by me, but it is well written. You can find the training routine in the scripts folder. I'll update the readme once I'll have a little time.
